defaults:
  - estimator: 
  - finetune:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Dataset related
sample_rate: 16000
segment: 10
stride: 2   # in seconds, how much to stride between training examples
pad: false   # if training sample is too short, pad it

# Dataset Augmentation
remix: false   # remix noise and clean
bandmask: 0.   # drop at most this fraction of freqs in mel scale
shift: 16000    # random shift, number of samples
shift_same: True   # shift noise and clean by the same amount
revecho: 0  # add reverb like augment

# Logging and printing, and does not impact training
num_prints: 5
device: cuda
num_workers: 16
verbose: 0
show: 0   # just show the model and its size and exit

# Checkpointing, by default automatically load last checkpoint
checkpoint: true
continue_from: 
      # Path the a checkpoint.th file to start from.
      # this is not used in the name of the experiment!
      # so use a dummy=something not to mixup experiments.
continue_best: false  # continue from best, not last state if continue_from is set.
continue_pretrained:  # use either dns48, dns64 or master64 to fine tune from pretrained-model
restart: false # Ignore existing checkpoints
save_checkpoints: True
checkpoint_file: checkpoint.th
best_file: best.th  # will contain only best model at any point
history_file: history.json
samples_dir: samples
save_again: false # if true, only load checkpoint and save again, useful to reexport best.th

# Other stuff
seed: 2022
dummy: # use this if you want twice the same exp, with a different name

# Evaluation stuff
pesq: True # compute pesq?
eval_every: 5  # compute test metrics every so epochs
dry: 0.  # dry/wet knob value at eval
streaming: False  # use streaming evaluation for Demucs

# Optimization related
optim: adam
lr: 3e-4
gradient_clip: True
beta2: 0.999
loss: l1
grad_max_norm: 0.01
acoustic_model_path:
acoustic_loss: True
acoustic_loss_only: False
ac_loss_weight: 0.1
ac_loss_type: l2
is_phoneme_weighted: True
phoneme_weight_path: 
phoneme_model_path: 
stft_loss: True
stft_sc_factor: .5
stft_mag_factor: .5
stft_loss_weight: 0.05
epochs: 10
batch_size: 32

# Models
model: demucs # either demucs or dwave
demucs:
fullsubnet:
PhonemeWeightEstimator:
AcousticEstimator:

# Egemaps stuff
acoustic_train_path:
acoustic_valid_path:
acoustic_test_path:

# phoneme logits stuff
ph_logits_train_path: 
ph_logits_valid_path: 
ph_logits_test_path: 


# Experiment launching, distributed
ddp: true
ddp_backend: nccl
rendezvous_file: ./rendezvous

# Internal config, don't set manually
rank:
world_size:

# Hydra config
hydra:
  run:
    dir: ./exp/exp_${hydra.job.override_dirname}
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        # Remove all paths, as the / in them would mess up things
        # Remove params that would not impact the training itself
        # Remove all slurm and submit params.
        # This is ugly I know...
        exclude_keys: [
          'hydra.job_logging.handles.file.filename',
          'demucs.causal','demucs.hidden','demucs.resample',
          'dset.train', 'dset.valid', 'dset.test', 'dset.noisy_json', 'dset.noisy_dir',
          'eval_every',
          'num_prints', 'continue_from', 'save_again',
          'device', 'num_workers', 'print_freq', 'restart', 'verbose',
          'log', 'ddp', 'ddp_backend', 'rendezvous_file', 'rank', 'world_size']
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr

  hydra_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr


# additional config
dset: 